### ISSUE TITLE
httpjson - support for headers

### ISSUE THREAD

**Issue by niriven** [influxdb/telegraf#426]
httpjson supports passing parameters, however it would be nice if it supported configuration of headers and setting them based on config similar to how the parameters are done

Looks like a new config section should be added, struct updated, and headers set at the req level with req.Header.Add(key, value)

Test update needed as well to cover this change

**Comment by palkan** [comment]
Should we provide headers on per server or per service base?
I guess, you want to use some kind of _authorization_ headers. Thus every server needs its own headers.

This requires some breaking changes to configuration, i.e.:

```toml
[[httpjson.services]]
  name = "mycollector"

  [[httpjson.services.servers]]
    url = "http://my.service.com/_stats"
   # as yet another nested list
   [[httpjson.services.servers.headers]]
      "X-API-KEY" = "qwerty"
```


ping @sparrc
